
# 린트 과정에서 무시할 파일 경로
excluded:
  - frameworks
  - Pods

whitelist_rules:

  - convenience_type
  - multiline_arguments
  - multiline_parameters
  - closure_spacing
  - empty_parameters
  - operator_usage_whitespace
  - redundant_type_annotation
  - syntactic_sugar
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - vertical_whitespace

  - control_statement
  - identifier_name
  - implicit_getter
  - large_tuple
  - legacy_constructor
  - line_length
  - multiple_closures_with_trailing_closure
  #- redundant_string_enum_value #비활성화
  - type_name
  - unused_optional_binding
  ## 자동 수정되는 규칙 ##
  - colon
  - empty_parentheses_with_trailing_closure
  - mark
  - no_space_in_method_call

identifier_name:
  min_length: 1
  max_length: 60
  allowed_symbols: [_]

line_length:
  warning: 110
  error: 200
  ignores_urls: true
  ignores_comments: true

