# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeeForCoding' do
  
  pod 'lottie-ios', '3.1.8'
  pod 'SnapKit', '5.0.1'
  pod 'Swinject', '2.7.1'
  
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'ReactorKit', git: 'https://github.com/ReactorKit/ReactorKit', branch: 'master', submodules: true
  pod 'RIBs', git: 'https://github.com/uber/RIBs.git', branch: 'master', submodules: true

  target 'CoffeeForCodingTests' do
    inherit! :search_paths
    
    pod 'Nimble', '8.1.2'
    pod 'Quick', '3.0.0'
    pod 'Stubber', '1.5.3'
    
  end

end
