name: UnitTest

on: [push]
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.3.1.app
    - name: Cocoapod
      run: |
        cd CoffeeForCoding
        pod install
    - name: iPhone 8 Test
      run: xcodebuild test -scheme CoffeeForCoding -workspace CoffeeForCoding/CoffeeForCoding.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8'
